<a href="https://colab.research.google.com/github/changsuk-oh/introduction-to-deep-learning/blob/main/2%EC%9E%A5_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EB%AA%A8%EB%8D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2장 신경망 모델

In [ ]:
# 예제 2.1 단층 신경망을 이용한 분류 모델(순차적 방식)

# 셋업(필요한 라이브러리나 클래스 불러옴)
import torch
import torch.nn as nn
torch.manual_seed(7)

# 모델 생성
model = nn.Sequential(
    nn.Linear(3, 2)   # 입력 특징 3개/출력층 뉴런 2개
)

print(model)

Sequential(
  (0): Linear(in_features=3, out_features=2, bias=True)
)


In [ ]:
# 모델의 계층 구조 확인
model._modules

{'0': Linear(in_features=3, out_features=2, bias=True)}

In [ ]:
# 내부 상태와 파라미터 확인
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.0403, -0.3478,  0.1838],
                      [ 0.1812, -0.3086, -0.0865]])),
             ('0.bias', tensor([-0.3382,  0.1498]))])

In [ ]:
# 가중치 확인
weight, bias = model.parameters()

w = weight.detach().numpy()  # 연산 그래프에서 분리하고 배열로 변환
b = bias.detach().numpy()

print(f"weight: {w.round(2)} \nbias: {b.round(2)}")

weight: [[ 0.04 -0.35  0.18]
 [ 0.18 -0.31 -0.09]] 
bias: [-0.34  0.15]


In [ ]:
# 예제 2.1 단층 신경망을 이용한 분류 모델(클래스 정의)

# 셋업
import torch
import torch.nn as nn

# 모델 정의
class SingleLayerModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(3, 2)

    def forward(self, x):
        y = self.fc(x)
        return y

# 모델 생성
model = SingleLayerModel()

print(model)

SingleLayerModel(
  (fc): Linear(in_features=3, out_features=2, bias=True)
)


In [ ]:
!pip install torchinfo

In [ ]:
# 모델 구조 요약
from torchinfo import summary

summary(model, input_size=(1, 3))  # 배치 크기 1, 입력 특징 3개

Layer (type:depth-idx)                   Output Shape              Param #
SingleLayerModel                         [1, 2]                    --
├─Linear: 1-1                            [1, 2]                    8
Total params: 8
Trainable params: 8
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# 예제 2.2 다층 신경망을 이용한 분류 모델(순차적 방식)

# 셋업
import torch
import torch.nn as nn
torch.manual_seed(7)

# 모델 생성
model = nn.Sequential(
    nn.Flatten(),   # 2차원 이미지를 1차원 벡터로 변환
    nn.Linear(9, 2),   # 은닉층 뉴런 2개
    nn.Linear(2, 3)   # 출력층 뉴런 3개
)

print(model)

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=9, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [ ]:
# 모델의 계층 구조 확인
model._modules

{'0': Flatten(start_dim=1, end_dim=-1),
 '1': Linear(in_features=9, out_features=2, bias=True),
 '2': Linear(in_features=2, out_features=3, bias=True)}

In [ ]:
# 내부 상태와 파라미터 확인
model.state_dict()

OrderedDict([('1.weight',
              tensor([[ 0.0233, -0.2008,  0.1061,  0.1046, -0.1782, -0.0500, -0.1953,  0.0865,
                       -0.0898],
                      [ 0.2342,  0.2366,  0.0340, -0.1421, -0.1958, -0.0366, -0.0938,  0.1469,
                       -0.2846]])),
             ('1.bias', tensor([ 0.3133, -0.2615])),
             ('2.weight',
              tensor([[ 0.5415, -0.1228],
                      [ 0.3637,  0.2756],
                      [ 0.0296,  0.1318]])),
             ('2.bias', tensor([0.5370, 0.1819, 0.3752]))])

In [ ]:
# 가중치 확인
for name, param in model.named_parameters():
    print(name, param.detach().numpy())

1.weight [[ 0.02328169 -0.20079789  0.10614114  0.10459352 -0.17815897 -0.04995906
  -0.19527599  0.08649091 -0.08978923]
 [ 0.2341789   0.23662877  0.03395681 -0.14210734 -0.19578707 -0.03660655
  -0.09380937  0.1469203  -0.28463206]]
1.bias [ 0.31327975 -0.26147565]
2.weight [[ 0.54147065 -0.12279231]
 [ 0.3637279   0.275556  ]
 [ 0.02959956  0.13184883]]
2.bias [0.5369828  0.18185243 0.37515363]


In [ ]:
# 출력층의 가중치 확인
print(model[2].weight, "\n")
print(model[2].bias)

Parameter containing:
tensor([[ 0.5415, -0.1228],
        [ 0.3637,  0.2756],
        [ 0.0296,  0.1318]], requires_grad=True) 

Parameter containing:
tensor([0.5370, 0.1819, 0.3752], requires_grad=True)


In [ ]:
# 예제 2.2 다층 신경망을 이용한 분류 모델(클래스 정의)

# 셋업
import torch
import torch.nn as nn

# 모델 정의
class MultiLayerModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(9, 2)
        self.fc2 = nn.Linear(2, 3)

    def forward(self, x):
        x = self.flatten(x)
        x = self.fc1(x)
        y = self.fc2(x)
        return y

# 모델 생성
model = MultiLayerModel()

print(model)

MultiLayerModel(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc1): Linear(in_features=9, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=3, bias=True)
)


In [ ]:
!pip install torchinfo

In [ ]:
# 모델 구조 요약
from torchinfo import summary

summary(model, input_size=(1, 3, 3))  # 배치 크기(1), 입력(3X3)

Layer (type:depth-idx)                   Output Shape              Param #
MultiLayerModel                          [1, 3]                    --
├─Flatten: 1-1                           [1, 9]                    --
├─Linear: 1-2                            [1, 2]                    20
├─Linear: 1-3                            [1, 3]                    9
Total params: 29
Trainable params: 29
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# 예제 2.3 활성화 함수에 따른 뉴런의 출력

import torch

# ReLU 함수 정의
def relu(net):
    if net >= 0:
        return net
    else:
        return 0

# LeakyReLU 함수 정의
def leaky_relu(net):
    if net >= 0:
        return net
    else:
        return 0.01 * net

# sigmoid 함수 정의
def sigmoid(net):
    return  1 / (1 + torch.exp(-net))

# tanh 함수 정의
def tanh(net):
    return (torch.exp(net) - torch.exp(-net)) / (torch.exp(net) + torch.exp(-net))

x = torch.tensor([1., 2.])   # 입력
w = torch.tensor([-1., 1.])   # 가중치

net = torch.dot(x, w)   # 입력 가중합

y1 = relu(net)   # ReLU 함수 출력
y2 = leaky_relu(net)   # LeakyReLU 함수 출력
y3 = sigmoid(net)   # sigmoid 함수 출력
y4 = tanh(net)   # tanh 함수 출력

print(f"net: {net}")
print(f"output of ReLU: {y1}")
print(f"output of LeakyReLU: {y2}")
print(f"output of sigmoid: {y3:.2f}")
print(f"output of tanh: {y4:.2f}")

net: 1.0
output of ReLU: 1.0
output of LeakyReLU: 1.0
output of sigmoid: 0.73
output of tanh: 0.76


In [ ]:
# 예제 2.4 활성화 함수에 따른 뉴런의 출력

import torch

# ReLU 함수 정의
def relu(net):
    if net >= 0:
        return net
    else:
        return 0

# LeakyReLU 함수 정의
def leaky_relu(net):
    if net >= 0:
        return net
    else:
        return 0.01 * net

# sigmoid 함수 정의
def sigmoid(net):
    return  1 / (1 + torch.exp(-net))

# tanh 함수 정의
def tanh(net):
    return (torch.exp(net) - torch.exp(-net)) / (torch.exp(net) + torch.exp(-net))

x = torch.tensor([1., 1., 2.])   # 입력
w = torch.tensor([0.5, 0.3, -0.5])   # 가중치

net = torch.dot(x, w)   # 입력 가중합

y1 = relu(net)   # ReLU 함수 출력
y2 = leaky_relu(net)   # LeakyReLU 함수 출력
y3 = sigmoid(net)   # sigmoid 함수 출력
y4 = tanh(net)   # tanh 함수 출력

print(f"net: {net:.2f}")
print(f"output of ReLU: {y1}")
print(f"output of LeakyReLU: {y2:.4f}")
print(f"output of sigmoid: {y3:.2f}")
print(f"output of tanh: {y4:.2f}")

net: -0.20
output of ReLU: 0
output of LeakyReLU: -0.0020
output of sigmoid: 0.45
output of tanh: -0.20


In [ ]:
# 예제 2.5 sigmoid 함수와 softmax 함수의 출력 비교

import torch

# sigmoid 함수 정의
def sigmoid(net):
    return  1 / (1 + torch.exp(-net))

# softmax 함수 정의
def softmax(net):
    return torch.exp(net) / torch.sum(torch.exp(net))

x =torch.tensor([[1., 1., 0.]])   # 입력
w = torch.tensor([[1., 2., 3.], [3., 2., 1.]])   # 가중치

net = torch.matmul(x, w.T)   # 입력 가중합

y1 = sigmoid(net)   # sigmoid 함수 출력
y2 = softmax(net)   # softmax 함수 출력

print(f"net: {net} \n")
print(f"y_sigmoid: {y1.numpy().round(4)} \n"
      f"sum of y_sigmoid: {torch.sum(y1):.4f} \n")
print(f"y_softmax: {y2.numpy().round(4)} \n"
      f"sum of y_softmax: {torch.sum(y2):.4f}")

net: tensor([[3., 5.]]) 

y_sigmoid: [[0.9526 0.9933]] 
sum of y_sigmoid: 1.9459 

y_softmax: [[0.1192 0.8808]] 
sum of y_softmax: 1.0000
