부록 텐서 연산

In [1]:
import torch
import numpy as np

In [ ]:
# shape 확인

# 0차원 텐서(스칼라)
a = torch.tensor(1)
print(a, a.shape, "\n")

# 1차원 텐서(벡터)
b = torch.tensor([1, 2, 3, 4, 5, 6])
print(b, b.shape, "\n")

# 2차원 텐서(행렬)
c = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(c, c.shape, "\n")

# 3차원 텐서
d = torch.tensor([[[1, 2, 3], [4, 5, 6]]])
print(d, d.shape)

tensor(1) torch.Size([]) 

tensor([1, 2, 3, 4, 5, 6]) torch.Size([6]) 

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3]) 

tensor([[[1, 2, 3],
         [4, 5, 6]]]) torch.Size([1, 2, 3])


In [ ]:
# reshape(shape 변환)

a = torch.arange(6)
print(a, a.shape, "\n")

b = a.reshape(2, 3)
print(b, b.shape, "\n")

c = torch.reshape(a, (2, 3))
print(c, c.shape, "\n")

d = c.reshape(-1)
print(d, d.shape)

tensor([0, 1, 2, 3, 4, 5]) torch.Size([6]) 

tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3]) 

tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3]) 

tensor([0, 1, 2, 3, 4, 5]) torch.Size([6])


In [ ]:
# flatten/view(1차원 텐서로 변환)

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a, a.shape, "\n")

b = a.flatten()
print(b, b.shape, "\n")

c = a.view(-1)
print(c, c.shape, "\n")

d = a.view(1, -1)   # a.reshape(1, -1)
print(f, f.shape, "\n")

e = d.view(2, 3)   # d.reshape(2, 3)
print(e, e.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3]) 

tensor([1, 2, 3, 4, 5, 6]) torch.Size([6]) 

tensor([1, 2, 3, 4, 5, 6]) torch.Size([6]) 

tensor([[1, 2, 3, 4, 5, 6]]) torch.Size([1, 6]) 

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])


In [ ]:
# squeeze/unsqueeze(차원 축소/추가)

a = torch.tensor([[1, 2, 3]])
print(a, a.shape, "\n")

b = a.squeeze()   # 차원 축소
print(b, b.shape, "\n")

c = b.unsqueeze(dim=0)   # 차원 추가
print(c, c.shape)

tensor([[1, 2, 3]]) torch.Size([1, 3]) 

tensor([1, 2, 3]) torch.Size([3]) 

tensor([[1, 2, 3]]) torch.Size([1, 3])


In [ ]:
# permute(차원 순서 변경)

a = torch.tensor([[[1, 2, 3], [4, 5, 6]]])
print(a, a.shape, "\n")

b = a.permute(2, 0, 1)
print(b, b.shape)

tensor([[[1, 2, 3],
         [4, 5, 6]]]) torch.Size([1, 2, 3]) 

tensor([[[1, 4]],

        [[2, 5]],

        [[3, 6]]]) torch.Size([3, 1, 2])


In [6]:
# 텐서-배열 변환

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a, "\n")

b = a.numpy()   # 넘파이 배열로 변환
print(b, "\n")

c = torch.from_numpy(b)   # 텐서로 변환
print(c, "\n")

d = torch.tensor(b)   # 텐서로 변환
print(d)

tensor([[1, 2, 3],
        [4, 5, 6]]) 

[[1 2 3]
 [4 5 6]] 

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# 텐서(GPU 연산)-배열(CPU 연산) 변환

# 연산에 사용할 디바이스 지정 (GPU 가능 시 cuda)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

a = torch.tensor([[1, 2, 3], [4, 5, 6]]).to(device)   # 선택된 디바이스로 텐서 이동
print(f"{a}  a is on {a.device} \n")

b = a.cpu().numpy()   # CPU로 이동한 후 넘파이 배열로 변환
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')  a is on cuda:0 

[[1 2 3]
 [4 5 6]]


In [8]:
# 텐서의 자료형

a = torch.tensor([1, 2, 3])   # 64비트 정수형
print(a,  a.dtype, "\n")

b = torch.tensor([1, 2, 3], dtype=torch.int32)   # 자료형 지정
print(b, "\n")

c = torch.tensor([1, 2, 3], dtype=torch.long)   # 자료형 지정
print(c, c.dtype, "\n")

d = torch.tensor([1., 2., 3.])   # 32비트 실수형
print(d, d.dtype, "\n")

e = torch.tensor([1, 2, 3], dtype=torch.float32)   # 자료형 지정
print(e, e.dtype)

tensor([1, 2, 3]) torch.int64 

tensor([1, 2, 3], dtype=torch.int32) 

tensor([1, 2, 3]) torch.int64 

tensor([1., 2., 3.]) torch.float32 

tensor([1., 2., 3.]) torch.float32


In [10]:
# int/float(자료형 변환)

a = torch.tensor([1., 2., 3.])   # 실수형
print(a, "\n")

b = a.int()   # 정수형으로 변환
print(b, "\n")

c = b.float()   # 실수형으로 변환
print(c)

tensor([1., 2., 3.]) 

tensor([1, 2, 3], dtype=torch.int32) 

tensor([1., 2., 3.])


In [21]:
# 인덱싱/슬라이싱(1차원 텐서의 요소 선택)

a = torch.arange(10)

print(a, "\n")
print(a[5], "\n")   # 인덱싱(특정 요소 선택)
print(a[-1], "\n")   # 인덱싱(맨 뒤 요소 선택)
print(a[:5], "\n")   # 슬라이싱(특정 범위의 요소 선택)
print(a[5:], "\n")   # 슬라이싱(특정 범위의 요소 선택)
print(a[a > 5])   # 불리언 마스킹(조건식을 만족하는 요소 선택)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

tensor(5) 

tensor(9) 

tensor([0, 1, 2, 3, 4]) 

tensor([5, 6, 7, 8, 9]) 

tensor([6, 7, 8, 9])


In [24]:
# 인덱싱/슬라이싱(2차원 텐서의 요소 선택)

a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8,9]])

print(a, "\n")
print(a[0], "\n")
print(a[2], "\n")
print(a[0][1], "\n")
print(a[0, 1], "\n")
print(a[1][1:])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 

tensor([1, 2, 3]) 

tensor([7, 8, 9]) 

tensor(2) 

tensor(2) 

tensor([5, 6])


In [26]:
# 불리언 텐서 생성

a = torch.arange(5)
print(a, "\n")

b = a > 2   # 조건식으로 불리언 텐서(False/True) 생성
print(b, "\n")

c = (a > 2).int()   # 불리언 텐서를 정수형 텐서(0/1)로 변환
print(c)

tensor([0, 1, 2, 3, 4]) 

tensor([False, False, False,  True,  True]) 

tensor([0, 0, 0, 1, 1], dtype=torch.int32)


In [27]:
# zeros/ones(0/1 텐서 생성)

a = torch.zeros((2, 3))   # 모든 요소가 0인 텐서 생성
print(a, "\n")

b = torch.ones((2, 3))   # 모든 요소가 1인 텐서 생성
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [34]:
# random(난수 텐서 생성)

torch.manual_seed(7)

a = torch.rand(2, 3)  # 균등 분포(0 ~ 1)
print(a, "\n")

b = torch.randn(2, 3)   # 정규 분포(평균 0, 표준편차 1)
print(b, "\n")

c = torch.normal(mean=0, std=1, size=(2, 3))   # 정규 분포(평균와 표준편차 지정)
print(c, "\n")

d = torch.randint(0, 10, (2,3))   # 균등 정수 분포
print(d)

tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251]]) 

tensor([[-1.2514, -1.8841,  0.4457],
        [-0.7068, -1.5750, -0.6318]]) 

tensor([[ 0.0212, -0.3602,  0.5662],
        [ 0.2142,  0.4963,  0.1196]]) 

tensor([[1, 0, 6],
        [3, 5, 6]])


In [35]:
# add/subtract/multiply/divide(사칙 연산)

a = torch.tensor([1, 2, 3, 4])
print(a, "\n")

b = torch.tensor([5, 6, 7, 8])
print(b, "\n")

c = a + b   # torch.add(a, b)
print(c, "\n")

d = a - b   # torch.sub(a, b)
print(d, "\n")

e = a * b   # torch.mul(a, b)
print(e, "\n")

f = a / b   # torch.div(a, b)
print(f)

tensor([1, 2, 3, 4]) 

tensor([5, 6, 7, 8]) 

tensor([ 6,  8, 10, 12]) 

tensor([-4, -4, -4, -4]) 

tensor([ 5, 12, 21, 32]) 

tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [38]:
# sum/sqrt/square/pow(연산 함수)

a = torch.tensor([1., 2., 3.])
print(a, "\n")

b = torch.sum(a)   # 합
print(b, "\n")

c = torch.sqrt(a)   # 제곱근
print(c, "\n")

d = torch.square(a)   # 제곱
print(d, "\n")

e = torch.pow(a, 3)   # 거듭 제곱(a**3)
print(e, "\n")

tensor([1., 2., 3.]) 

tensor(6.) 

tensor([1.0000, 1.4142, 1.7321]) 

tensor([1., 4., 9.]) 

tensor([ 1.,  8., 27.]) 



In [39]:
# exp/log(연산 함수)

a = torch.tensor([1., 2., 3.])
print(a, "\n")

b = torch.exp(a)   # 지수
print(b, "\n")

c = torch.log(a)   # 자연 로그(ln)
print(c, "\n")

d = torch.log2(a)   # 로그(밑수 2)
print(d, "\n")

e = torch.log10(a)   # 상용 로그(밑수 10)
print(e)

tensor([1., 2., 3.]) 

tensor([ 2.7183,  7.3891, 20.0855]) 

tensor([0.0000, 0.6931, 1.0986]) 

tensor([0.0000, 1.0000, 1.5850]) 

tensor([0.0000, 0.3010, 0.4771])


In [41]:
# min/max/median/mean/std/var(통계 함수)

a =torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.float32)
print(a, "\n")

b = torch.min(a)   # 최소값
print(b, "\n")

c = torch.max(a)   # 최대값
print(c, "\n")

d = torch.median(a)   # 중간값
print(d, "\n")

e = torch.mean(a)   # 평균
print(e, "\n")

f = torch.std(a)   # 표준편차
print(f, "\n")

g = torch.var(a)   # 분산
print(g)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) 

tensor(1.) 

tensor(9.) 

tensor(5.) 

tensor(5.) 

tensor(2.7386) 

tensor(7.5000)


In [46]:
# argmax(최대값 인덱스)

a = torch.tensor([[1, 3, 5], [7, 9, 2], [4, 6, 8]])
print(a, "\n")

b = torch.argmax(a, dim=0)   # 최대값의 인덱스
print(b, "\n")

c = torch.argmax(a, dim=1)
print(c, "\n")

d = torch.argmax(a, dim=-1)
print(d, "\n")

e = torch.max(a, dim=1)   # 최대값
print(e)

tensor([[1, 3, 5],
        [7, 9, 2],
        [4, 6, 8]]) 

tensor([1, 1, 2]) 

tensor([2, 1, 2]) 

tensor([2, 1, 2]) 

torch.return_types.max(
values=tensor([5, 9, 8]),
indices=tensor([2, 1, 2]))


In [47]:
# 브로드캐스팅(shape이 다른 텐서의 연산에서 차원이 자동으로 확장)

a =torch.tensor([1, 2, 3])   # shape=(3, )
print(a, "\n")

b = torch.tensor([5])   # shape=(1, )
print(b, "\n")

c = a + b   # b = torch.tensor([5, 5, 5])로 확장되어 연산
print(c)

tensor([1, 2, 3]) 

tensor([5]) 

tensor([6, 7, 8])


In [48]:
# transpose(전치 행렬)

a =torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a, "\n")

b = a.t()   # a.T
print(b, "\n")

c = a.transpose(0, 1)
print(c, "\n")

d = torch.transpose(a, 0, 1)
print(d)

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor([[1, 4],
        [2, 5],
        [3, 6]]) 

tensor([[1, 4],
        [2, 5],
        [3, 6]]) 

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [49]:
# dot(내적)

a = torch.tensor([1, 2, 3, 4])
print(a, "\n")

b = torch.tensor([5, 6, 7, 8])
print(b, "\n")

c = torch.dot(a, b)
print(c, "\n")

d = torch.matmul(a, b)
print(d)

tensor([1, 2, 3, 4]) 

tensor([5, 6, 7, 8]) 

tensor(70) 

tensor(70)


In [50]:
# matmul(행렬곱)

a = torch.tensor([[1, 2], [3, 4]])
print(a, "\n")

b = torch.tensor([[5, 6], [7, 8]])
print(b, "\n")

c = torch.matmul(a, b)
print(c)

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]]) 

tensor([[19, 22],
        [43, 50]])


In [54]:
# cat/stack(텐서 결합)

a = torch.tensor([1, 2, 3])
print(a, "\n")

b = torch.tensor([4, 5, 6])
print(b, "\n")

c = torch.cat((a, b))   # 텐서 연결
print(c, "\n")

d = torch.stack((a, b))   # 새로운 축으로 텐서 쌓음
print(d)

tensor([1, 2, 3]) 

tensor([4, 5, 6]) 

tensor([1, 2, 3, 4, 5, 6]) 

tensor([[1, 2, 3],
        [4, 5, 6]])


In [55]:
# list/dict(리스트/딕셔너리 생성)

a = torch.tensor([1, 2, 3])
print(a, "\n")

b = torch.tensor([4, 5, 6])
print(b, "\n")

c = list(zip(a, b))   # 튜플로 묶어 리스트 생성
print(c, "\n")

d = dict(zip(a, b))   # 딕셔너리 생성
print(d)

tensor([1, 2, 3]) 

tensor([4, 5, 6]) 

[(tensor(1), tensor(4)), (tensor(2), tensor(5)), (tensor(3), tensor(6))] 

{tensor(1): tensor(4), tensor(2): tensor(5), tensor(3): tensor(6)}


In [56]:
# split/chunk(텐서 분할)

a = torch.tensor([1, 2, 3, 4, 5, 6])
print(a, "\n")

b = torch.split(a, split_size_or_sections=2)   # 특정 크기(2개씩)로 분할
print(b, "\n")

c = torch.split(a, split_size_or_sections=3)   # 3개씩 분할
print(c, "\n")

d = torch.chunk(a, chunks=2)   # 갯수(2개)로 분할
print(d, "\n")

e = torch.chunk(a, chunks=3)   # 3개로 분할
print(e)

tensor([1, 2, 3, 4, 5, 6]) 

(tensor([1, 2]), tensor([3, 4]), tensor([5, 6])) 

(tensor([1, 2, 3]), tensor([4, 5, 6])) 

(tensor([1, 2, 3]), tensor([4, 5, 6])) 

(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))


In [79]:
# sort(정렬)

a = torch.tensor([1, 3, 5, 2, 4])
print(a, "\n")

b = torch.sort(a)   # 오름차순 정렬
print(b, "\n")

c, _ = torch.sort(a)   # 오름차순 정렬
print(c, "\n")

d, _ = torch.sort(a, descending=True)   # 내림차순 정렬
print(d)

tensor([1, 3, 5, 2, 4]) 

torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 3, 1, 4, 2])) 

tensor([1, 2, 3, 4, 5]) 

tensor([5, 4, 3, 2, 1])


In [77]:
# item(스칼라 값 추출)

a = torch.tensor([1, 2, 3])
print(a, "\n")

b = a[1]   # 0차원 텐서
print(b, "\n")

c = a[1].item()   # 텐서에서 스칼라 값 추출
print(c)

tensor([1, 2, 3]) 

tensor(2) 

2
